name: Build, validate and deploy ASP.Net Core app to Azure Web App - minimalapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Show directory tree before build
        run: |
          echo "📁 Conteúdo inicial do repositório:"
          ls -R

      - name: Build with dotnet
        run: |
          echo "🏗️ Iniciando build do projeto..."
          dotnet build ./Api/minimal-api.csproj --configuration Release

      - name: Publish with dotnet
        run: |
          echo "📦 Publicando projeto..."
          dotnet publish ./Api/minimal-api.csproj -c Release -o ./myapp

      - name: Verify published files
        run: |
          echo "📂 Arquivos gerados na pasta ./myapp:"
          ls -R ./myapp || echo "❌ Nenhum arquivo encontrado em ./myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Verify artifact content
        run: |
          echo "📦 Verificando conteúdo baixado do artefato:"
          ls -R || echo "❌ Nenhum arquivo encontrado no artefato baixado."

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B0D1A9B3AB1E4DFB85B3EB9ECEA57810 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_09231F8657B045A4BA2FB1ADEC1D6242 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7D605DEDA28D441DAAF3D49D0D1B98D2 }}

      - name: List files before deploy
        run: |
          echo "🧾 Listando arquivos antes do deploy..."
          ls -R

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'minimalapi'
          slot-name: 'Production'
          package: .
